version: "3"

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8000:8080"
      - "8001:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - "./spark-notebooks/lab16/data:/data"

