version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper

  spark-master:
    image: bitnami/spark:3.5.0
    hostname: spark
    volumes:
      - ./bronze:/opt/prefect/spark-warehouse/delta_bronze
      - ./silver:/opt/prefect/spark-warehouse/delta_silver
      - ./agg_sol_cam_gold:/opt/prefect/spark-warehouse/agg_sol_cam_gold
      - ./avg_photos_per_sol_gold:/opt/prefect/spark-warehouse/avg_photos_per_sol_gold
      - ./active_periods_gold:/opt/prefect/spark-warehouse/active_periods_gold
      - ./result:/opt/prefect/spark-warehouse/result
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=4041
      - SPARK_OPTS=--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
    ports:
      - "7077:7077"
      - "4041:4041"

  spark-worker-1:
    image: bitnami/spark:3.5.0
    volumes:
      - ./bronze:/opt/prefect/spark-warehouse/delta_bronze
      - ./silver:/opt/prefect/spark-warehouse/delta_silver
      - ./agg_sol_cam_gold:/opt/prefect/spark-warehouse/agg_sol_cam_gold
      - ./avg_photos_per_sol_gold:/opt/prefect/spark-warehouse/avg_photos_per_sol_gold
      - ./active_periods_gold:/opt/prefect/spark-warehouse/active_periods_gold
      - ./result:/opt/prefect/spark-warehouse/result
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
      
  spark-worker-2:
    image: bitnami/spark:3.5.0
    volumes:
      - ./bronze:/opt/prefect/spark-warehouse/delta_bronze
      - ./silver:/opt/prefect/spark-warehouse/delta_silver
      - ./agg_sol_cam_gold:/opt/prefect/spark-warehouse/agg_sol_cam_gold
      - ./avg_photos_per_sol_gold:/opt/prefect/spark-warehouse/avg_photos_per_sol_gold
      - ./active_periods_gold:/opt/prefect/spark-warehouse/active_periods_gold
      - ./result:/opt/prefect/spark-warehouse/result
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "8083:8081"

  spark-notebook:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./bronze:/opt/prefect/spark-warehouse/delta_bronze
      - ./silver:/opt/prefect/spark-warehouse/delta_silver
      - ./agg_sol_cam_gold:/opt/prefect/spark-warehouse/agg_sol_cam_gold
      - ./avg_photos_per_sol_gold:/opt/prefect/spark-warehouse/avg_photos_per_sol_gold
      - ./active_periods_gold:/opt/prefect/spark-warehouse/active_periods_gold
      - ./result:/opt/prefect/spark-warehouse/result
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_OPTS=--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
    command: start-notebook.sh --NotebookApp.token=''

  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  prefect:
    build: .
    restart: always
    volumes:
      - prefect:/root/.prefect
      - ./prefect:/opt/prefect/flows
      - ./bronze:/opt/prefect/spark-warehouse/delta_bronze
      - ./silver:/opt/prefect/spark-warehouse/delta_silver
      - ./agg_sol_cam_gold:/opt/prefect/spark-warehouse/agg_sol_cam_gold
      - ./avg_photos_per_sol_gold:/opt/prefect/spark-warehouse/avg_photos_per_sol_gold
      - ./active_periods_gold:/opt/prefect/spark-warehouse/active_periods_gold
      - ./result:/opt/prefect/spark-warehouse/result
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database

volumes:
  prefect:
  db:

